name: Lint Python
on:
  workflow_call:
    outputs:
      source-files: 
        description: "Whether the changes affect source files"
        value: ${{ jobs.files.outputs.source-files }}
  # Because we have a uv.lock file, we can also use this workflow to lint ourselves.
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  files:
    runs-on: ubuntu-latest
    outputs:
      source-files: ${{ steps.filter.outputs.source-files }}
    steps:
      - name: Begin snap installs of common linters
        id: snap-install
        run: |
          echo -n "jobs=$(sudo snap install --no-wait codespell ruff shellcheck)" >> $GITHUB_OUTPUT
      - name: Check out code
        uses: actions/checkout@v5
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          # Combine multiple negation checks into a union (¬A ∧ ¬B ∧ ¬C), because individual entries are checked independently (A ∨ B ∨ C).
          # If we ever need to filter only for docs, glob 'docs/**/*' and '**/*.md'
          filters: |
            source-files:
              - '!({docs/**,*.md,**/*.md})'
      - name: Set up uv with caching
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up linters
        run: |
          for job in ${{ steps.snap-install.outputs.jobs }}; do
            sudo snap watch $job
          done

          # Try setting up the linters, but if it breaks try again after an apt update.
          # It's written this way because mostly we don't need apt-get update and it just
          # makes the job take longer, but when we do need it it's because a package deb
          # got removed that makes the linter setup fail. This gets fixed automatically
          # when GitHub rebuilds the image.
          if ! make -j setup-lint; then
            sudo apt-get update
            make -j setup-lint
          fi
      - name: Run linters
        if: steps.filter.outputs.source-files == 'true'
        run: make -k lint
      - name: Run documentation linters
        if: steps.filter.outputs.source-files == 'false'
        run: make -k docs-lint
