name: QA self-test
on:
  pull_request:

jobs:
  lint-python:
    uses: ./.github/workflows/lint-python.yaml
  test-python:
    uses: ./.github/workflows/test-python.yaml
    needs: lint-python
    if: ${{ (needs.lint-python.outputs.src == 'true' && needs.lint-python.outputs.docs == 'false') || (needs.lint-python.outputs.src == 'true' && needs.lint-python.outputs.docs == 'true') }}
  test-python-custom:
    uses: ./.github/workflows/test-python.yaml
    needs: lint-python
    if: ${{ (needs.lint-python.outputs.src == 'true' && needs.lint-python.outputs.docs == 'false') || (needs.lint-python.outputs.src == 'true' && needs.lint-python.outputs.docs == 'true') }}
    with:
      # Test on many OS's to ensure that these workflows work everywhere.
      # Also ensure we can add a list of tags for self-hosted runners.
      fast-test-platforms: '[["jammy", "amd64"], ["noble", "arm64"], "ubuntu-22.04", "windows-latest", "macos-latest"]'
      fast-test-python-versions: '["3.14"]'
      slow-test-platforms: '["ubuntu-latest"]'
      slow-test-python-versions: '["3.14"]'
      lowest-python-version: "3.8"
      lowest-python-platform: '["jammy", "arm64"]'
      use-lxd: true
      pytest-markers: smoketest and not steamtest
      setup-vars: SETUP_EXTRA=1
  test-python-as-root:
    uses: ./.github/workflows/test-python.yaml
    needs: lint-python
    if: ${{ (needs.lint-python.outputs.src == 'true' && needs.lint-python.outputs.docs == 'false') || (needs.lint-python.outputs.src == 'true' && needs.lint-python.outputs.docs == 'true') }}
    with:
      # Test on many OS's to ensure that these workflows work everywhere.
      # Also ensure we can add a list of tags for self-hosted runners.
      fast-test-platforms: '["ubuntu-latest"]'
      fast-test-python-versions: '["3.14"]'
      slow-test-platforms: '["ubuntu-latest"]'
      slow-test-python-versions: '["3.14"]'
      lowest-python-version: "3.8"
      lowest-python-platform: "ubuntu-latest"
      test-command-prefix: sudo # Test that we can run with sudo.
